BEGIN TRANSACTION;
INSERT INTO escola (nome, endereco) VALUES ('EMEF PROF. AMAURY PACHECO', 'End.: Rua Izauro Pigozzi, 87 - Jardim Bandeirantes');
INSERT INTO escola (nome, endereco) VALUES ('EMEF PROF. AMÉRICO CAPELOZZA', 'End.: Rua Pacaembu, 691 - Bairro Jardim Lavínia');
INSERT INTO escola (nome, endereco) VALUES ('EMEF PROF. ANTÔNIO RIBEIRO', 'End.: Rua Benedito Mendes Faria, 450-A - Bairro Nova Marília');
INSERT INTO escola (nome, endereco) VALUES ('EMEF PROF. CÉLIO CORRADI', 'End.: Rua Belém, 675 - Bairro Vila Altaneira');
INSERT INTO escola (nome, endereco) VALUES ('EMEF PROFª EDMÉA BRAZ ROJO SOLA', 'End.: Rua Nicolino Roselli, 720 - Bairro Lorenzetti');
INSERT INTO escola (nome, endereco) VALUES ('EMEF PROFª GERALDA CÉSAR VILARDI', 'End.: Rua Amador Bueno, 1915 - Bairro José Teruel Martinez');
INSERT INTO escola (nome, endereco) VALUES ('EMEF GOVERNADOR MÁRIO COVAS', 'End.: Rua Manoel Pinheiro Mattos, 840 - Bairro Jardim Julieta');
INSERT INTO escola (nome, endereco) VALUES ('EMEF PROF. ISALTINO DE CAMPOS', 'End.: Rua Leonor Mazali, 105 - Bairro Parque Nova Almeida');
INSERT INTO escola (nome, endereco) VALUES ('EMEF PROFª MYRTHES PUPO NEGREIROS', 'End.: Rua Fernando Fontana, 195 - Bairro Costa e Silva');
INSERT INTO escola (nome, endereco) VALUES ('EMEF PROF. NELSON GABALDI', 'End.: Rua Amador Bueno, 1165 - Bairro Chico Mendes');
INSERT INTO escola (nome, endereco) VALUES ('EMEF PROFª NICÁCIA GARCIA GIL', 'End.: Rua José Clemente Ribeiro, 280 - Bairro Jardim Marajó');
INSERT INTO escola (nome, endereco) VALUES ('EMEF PROF. PAULO REGLUS NEVES FREIRE', 'End.: Rua José Cunha de Oliveira, 50 - Bairro Jd. Teotônio Vilela');
INSERT INTO escola (nome, endereco) VALUES ('EMEF PROFª RENY PEREIRA CORDEIRO', 'End.: Rua Alexandre Chaia, 865 – Bairro Jardim Esplanada');
INSERT INTO escola (nome, endereco) VALUES ('EMEF ROBERTO CAETANO CIMINO', 'End.: Av. José Jorente, 51 - Bairro Alcir Raineri');
INSERT INTO escola (nome, endereco) VALUES ('EMEF PROFª SOFIA TEIXEIRA BARBOSA', 'End.: Av. Pedro Alberto Tolentino, 520 - Residencial Montana');
INSERT INTO escola (nome, endereco) VALUES ('EMEFEI: PROF. ANTONIO GARCIA EGÉA', 'End.: Rua Getúlio Vargas, 40 - Distrito de Amadeu Amaral');
INSERT INTO escola (nome, endereco) VALUES ('EMEFEI: CHICO XAVIER', 'End.: Av. Maria Fernandes Cavallari, 2500 - Bairro Jardim Cavallari');
INSERT INTO escola (nome, endereco) VALUES ('E.E 17 DE SETEMBRO', 'Rua Rodolfo Lara Campos,1129 – B.Flândria');
INSERT INTO escola (nome, endereco) VALUES ('E.E ABEL AUGUSTO FRAGATA', 'Rua Aymorés, 72 – Bairro Salgado Filho');
INSERT INTO escola (nome, endereco) VALUES ('E.E ALCYR ROSA LIMA, Prof.', 'Rua Martin Afonso de Souza,440 – V.Araceli');
INSERT INTO escola (nome, endereco) VALUES ('E.E ALCIR RAINERI, JD.', 'Av. Alcebíades Spadotto, 165 – Jd. Alcir Raineri');
INSERT INTO escola (nome, endereco) VALUES ('E.E AMAURY PACHECO, Prof.', 'Rua Izauro Pigozzi, s/n-Jardim Eldorado');
INSERT INTO escola (nome, endereco) VALUES ('E.E AMÉLIA LOPES ANDERS, Profª.', 'Rua Pedro M. Parra, 470 –B. Santa Antonieta');
INSERT INTO escola (nome, endereco) VALUES ('E.E AMÍLCARE MATTEI, Prof.', 'Av.Brigadeiro E. Gomes, 265-Jd Maria Izabel');
INSERT INTO escola (nome, endereco) VALUES ('E.E ANTÔNIO AUGUSTO NETTO', 'Rua Carlos Santilli, 245 – Parque São Jorge');
INSERT INTO escola (nome, endereco) VALUES ('E.E ANTÔNIO DAUN', 'Rua Pedro Porfírio Franco,167-B.Stª Terezinha');
INSERT INTO escola (nome, endereco) VALUES ('E.E ANTÔNIO DE BAPTISTA, Prof.', 'Rua Washington Luiz, 1019- B.Cast. Branco');
INSERT INTO escola (nome, endereco) VALUES ('E.E ANTÔNIO GOMES DE OLIVEIRA, Prof.', 'Rua Nicolino Roseli, 75 – Bairro Paulista');
INSERT INTO escola (nome, endereco) VALUES ('E.E ANTÔNIO REGINATO, Prof.', 'Rua Corifeu ª Marques,807 – B.Palmital Prol');
INSERT INTO escola (nome, endereco) VALUES ('E.E APARECIDA LOPES RAMOS, Profª.', 'Av. Max Wirth, 308 – Bairro Centro');
INSERT INTO escola (nome, endereco) VALUES ('E.E CASTRO ALVES', 'Av. Paulista, 414 – B. Centro​ ​');
INSERT INTO escola (nome, endereco) VALUES ('E.E CULTURA E LIBERDADE', 'Rua Dr.José de Moura Resende,400-.Centro​');
INSERT INTO escola (nome, endereco) VALUES ('E.E DIRCE BELUZZO DE CAMPOS, Profª.', 'Av. Paulista, 920 – B. Centro​');
INSERT INTO escola (nome, endereco) VALUES ('E.E ERMELINDA CLARICE  SANCHES, Profª.', 'Rua Ângelo Marzola, 219 – Centro​ ​');
INSERT INTO escola (nome, endereco) VALUES ('E.E GERALDO ZANCOPÉ, Prof.', 'Rua América, 115 – Vila Palmital');
INSERT INTO escola (nome, endereco) VALUES ('E.E GRACIEMA BAGANHA RIBEIRO', 'Rua D. Ayda Baganha Ferreira,1086-S Terezinha ​​');
INSERT INTO escola (nome, endereco) VALUES ('E.E HATSUE TOYOTA', 'Rua Carlos Ferrari, 1400 – Vila Rebelo​ ​');
INSERT INTO escola (nome, endereco) VALUES ('E.E HILMAR MACHADO DE OLIVEIRA', 'Rua Fausto Floriano deToledo,35- Centro​');
INSERT INTO escola (nome, endereco) VALUES ('E.E IZIDORO DAUN', 'Rua Manoel Quito, 600 – Bairro Centro​ ​');
INSERT INTO escola (nome, endereco) VALUES ('E.E JOÃO WALFREDO ROTHERMUND, Pe.', 'Rua Gildo Bonato, 277 – Jardim Planalto​ ​');
INSERT INTO escola (nome, endereco) VALUES ('E.E JOSÉ ALFREDO DE ALMEIDA', 'Av. Tomé de Souza, 05 Jardim Continental');
INSERT INTO escola (nome, endereco) VALUES ('E.E JOSÉ​ AMBRÓSIO DOS SANTOS', 'Rua José Manzano Garcia, 555 – B. Centro​');
INSERT INTO escola (nome, endereco) VALUES ('E.E JOSÉ​ AUGUSTO BARTHOLO', 'Rua Girassol, 301 – Distrito Avencas – CEP: 17532-000 –');
INSERT INTO escola (nome, endereco) VALUES ('E.E JOSÉ CARLOS MONTEIRO', 'Rua 7 de setembro, 967 – Júlio Mesquita ​');
INSERT INTO escola (nome, endereco) VALUES ('E.E LOURENÇO DE ALMEIDA SENNE, Dr.', 'Rua Pio XII, 397 B. Hermínio Firmino Polon​ ​ – CEP: 17507-070 –');
INSERT INTO escola (nome, endereco) VALUES ('E.E LYDIA YVONE GOMES MARQUES, Profª.', 'Av.Maria Izabel, 550 – Bairro Labienópolis   – CEP: 17400-000 – Garça/SP');
INSERT INTO escola (nome, endereco) VALUES ('E.E MARIA CECÍLIA FERRAZ DE FREITAS, Profª.', 'Rua João Batista Marinho,70-B.Nova Marília');
INSERT INTO escola (nome, endereco) VALUES ('E.E NEUZA MARIA MARANA FEIJÃO, Profª.', 'Rua Gonçalves Dias, 70 – Distrito Lácio – CEP: 17539-000');
INSERT INTO escola (nome, endereco) VALUES ('E.E NORMA MÔNICO TRUZZI, Profª.', 'Rua Brasil,455 – Dist. Jafa – CEP: 17405-000');
INSERT INTO escola (nome, endereco) VALUES ('E.E ORACINA CORRÊA DE MORAES RODINE, Profª.', 'Rua Humberto R.Alves,275 – Jardim América – CEP: 17505-300');
INSERT INTO escola (nome, endereco) VALUES ('E.E RAFAEL PAES DE BARROS, Doutor', 'Rua Paulo Mariano Pires,81 – Bairro Centro – CEP: 17410-000');
INSERT INTO escola (nome, endereco) VALUES ('E.E REIKO UEMURA TSUNOKAWA, Profª.', 'Rua Antonio Ribeiro dos Santos,134 – N.H.J.K – CEP: 17511-710');
INSERT INTO escola (nome, endereco) VALUES ('E.E RUTH MAMEDE DE GODOY, Profª.', 'Rua Kaniti Yamane, 165- Distrito de Rosália – CEP: 17535-044');
INSERT INTO escola (nome, endereco) VALUES ('E.E SANTA ANTONIETA, Jd.', 'Rua Leonor Mazalli, 11 – CEP: 17512-420');
INSERT INTO escola (nome, endereco) VALUES ('E.E SEBASTIANA ULIAN PESSINE, Profª. – CEEJA', 'Rua 24 de dezembro, 162 – V. Barbosa – CEP: 17501-460');
INSERT INTO escola (nome, endereco) VALUES ('E.E SEBASTIÃO MÔNACO, Ver.', 'Rua Amador Bueno, 956 – Vila Comerciários II – CEP: 17527-622');
INSERT INTO escola (nome, endereco) VALUES ('E.E SYLVIA RIBEIRO DE CARVALHO, Profª.', 'Rua Nair R.Gutierrez, 345 -B. Nova Marília – CEP: 17523-150');
INSERT INTO escola (nome, endereco) VALUES ('E.E VITU GIORGI, Dona', 'Rua Washington Luiz, 85-A – Centro');
INSERT INTO escola (nome, endereco) VALUES ('E.E WALDEMAR MONIZ DA ROCHA BARROS, Dr.', 'Rua Henrique Dias, 854 – B.Fco. A Fernandes');
INSERT INTO escola (nome, endereco) VALUES ('E.E WANDA HELENA TOPPAN NOGUEIRA, Profª.', 'Rua João P.C. Padilha, s/n-.B. CECAP Aeroporto');
COMMIT;
